### ISSUE TITLE
something about train

### ISSUE THREAD

**Issue by zzy0724** [embracesource-cv-com/FCHD#1]
hello,l used offical code of FCHD to train,but the result model is not good.Model test accuracy is very low,Did you do well in your version?if your result is good ,What did you change?
Thankyou!

**Comment by ybcc2015** [comment]
Hi @zzy0724, sorry to reply you so late, I am busy recently.
In my version, the trained model works well. The model parameters and hyperparameter are the same as the official code. I haven't trained with official code before and you can have a try with my code.
