### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by mzk-cyber106808** [embracesource-cv-com/FCHD#2]
你好，请问你有与训练模型相配套的测试程序吗？我用原来版本的测试程序head_detection_demo.py一直报错，谢谢！

**Comment by ybcc2015** [comment]
你好，predict.py用来预测

**Comment by mzk-cyber106808** [comment]
你好，我训练模型的时候最多只能训练到epoch=2的时候，当第3次训练快结束的时候，就出现MemoryError: Unable to allocate array with shape (3, 480, 640) and data type float64，但我看了一下内存占用没超过30％。
